export const REGION_CODES = [
  "AD",
  "AE",
  "AF",
  "AL",
  "AM",
  "AO",
  "AR",
  "AT",
  "AU",
  "AZ",
  "BA",
  "BB",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BO",
  "BR",
  "BY",
  "CA",
  "CD",
  "CG",
  "CH",
  "CI",
  "CL",
  "CM",
  "CN",
  "CO",
  "CR",
  "CU",
  "CV",
  "CY",
  "CZ",
  "DE",
  "DK",
  "DO",
  "DZ",
  "EC",
  "EE",
  "EG",
  "ES",
  "FI",
  "FR",
  "GA",
  "GB",
  "GE",
  "GH",
  "GM",
  "GN",
  "GQ",
  "GR",
  "GT",
  "HN",
  "HR",
  "HT",
  "HU",
  "ID",
  "IE",
  "IL",
  "IN",
  "IQ",
  "IR",
  "IS",
  "IT",
  "JM",
  "JO",
  "JP",
  "KE",
  "KR",
  "KW",
  "KZ",
  "LB",
  "LI",
  "LT",
  "LU",
  "LV",
  "MA",
  "MC",
  "MD",
  "ME",
  "MG",
  "MK",
  "ML",
  "MR",
  "MT",
  "MX",
  "MY",
  "MZ",
  "NG",
  "NI",
  "NL",
  "NO",
  "NZ",
  "PA",
  "PE",
  "PL",
  "PR",
  "PT",
  "PY",
  "QA",
  "RO",
  "RS",
  "RU",
  "SA",
  "SC",
  "SE",
  "SI",
  "SK",
  "SN",
  "SV",
  "TH",
  "TN",
  "TR",
  "UA",
  "UG",
  "US",
  "UY",
  "UZ",
  "VE",
  "VN",
  "ZA",
  "ZM",
  "ZW"
];

export const COUNTRY_ALIASES: Record<string, string[]> = {
  Argentina: ["Argentina", "Argentine"],
  Australia: ["Australia", "Australie"],
  Austria: ["Austria"],
  Belgium: ["Belgium", "Belgio", "Bélgica", "Belgique", "Belgien"],
  Bosnia: ["Bosnia", "Bosnia ed Erzegovina", "Bosnia and Herzegovina"],
  Brazil: ["Brazil", "Brasile", "Brasil", "Bresil", "Brésil", "Brasilien"],
  Cameroon: ["Cameroon", "Camerun", "Camerún", "Cameroun", "Kamerun"],
  "Cape Verde": ["Cape Verde", "Capo Verde", "Cabo Verde", "Cap Vert", "Kap Verde"],
  Chile: ["Chile", "Cile"],
  Colombia: ["Colombia"],
  "Costa Rica": ["Costa Rica"],
  Croatia: ["Croatia", "Croazia", "Croacia", "Croatie", "Kroatien", "Croácia"],
  "DR Congo": [
    "DR Congo",
    "RD Congo",
    "Congo DR",
    "Congo RD",
    "Democratic Republic of Congo",
    "Repubblica Democratica del Congo",
    "República Democrática del Congo",
    "République démocratique du Congo"
  ],
  Denmark: ["Denmark", "Danimarca", "Dinamarca", "Danemark", "Dänemark"],
  Ecuador: ["Ecuador"],
  Egypt: ["Egypt", "Egitto", "Egipto", "Égypte", "Agypten", "Ägypten", "Egito"],
  England: ["England", "Inghilterra", "Inglaterra", "Angleterre"],
  France: ["France", "Francia", "França", "Frankreich"],
  Germany: ["Germany", "Germania", "Alemania", "Allemagne", "Deutschland", "Alemanha"],
  Ghana: ["Ghana"],
  "Great Britain": ["United Kingdom", "Regno Unito", "Gran Bretagna", "Great Britain", "UK"],
  "Ivory Coast": ["Ivory Coast", "Costa d'Avorio", "Costa d’Avorio", "Cote d Ivoire", "Côte d'Ivoire", "Côte d’Ivoire"],
  Italy: ["Italy", "Italia", "Italie", "Italien", "Itália"],
  Japan: ["Japan", "Giappone", "Japón", "Japon", "Japonia"],
  Mexico: ["Mexico", "Messico", "México", "Mexique", "Mexiko"],
  Morocco: ["Morocco", "Marocco", "Marruecos", "Maroc", "Marokko", "Marrocos"],
  Netherlands: ["Netherlands", "Olanda", "Paesi Bassi", "Holanda", "Países Bajos", "Paises Bajos", "Pays Bas", "Pays-Bas", "Holland", "Niederlande"],
  "New Zealand": ["New Zealand", "Nuova Zelanda", "Nueva Zelanda", "Nouvelle-Zélande", "Nouvelle Zelande", "Neuseeland"],
  Nigeria: ["Nigeria"],
  Poland: ["Poland", "Polonia", "Polska", "Pologne", "Polen", "Polônia"],
  Portugal: ["Portugal", "Portogallo"],
  "Saudi Arabia": ["Saudi Arabia", "Arabia Saudita", "Arabia Saudí", "Arabie Saoudite", "Saudi-Arabien"],
  Scotland: ["Scotland", "Scozia", "Escocia", "Écosse", "Schottland"],
  Senegal: ["Senegal"],
  Serbia: ["Serbia"],
  "South Africa": ["South Africa", "Sudafrica", "Afrique du Sud", "Südafrika"],
  "South Korea": ["South Korea", "Corea del Sud", "Corea Sud", "Korea Republic", "Republic of Korea", "Repubblica di Corea", "Corea"],
  Spain: ["Spain", "Spagna", "España", "Espana", "Espagne", "Spanien", "Espanha"],
  Switzerland: ["Switzerland", "Svizzera", "Suiza", "Suisse", "Schweiz", "Suiça"],
  Tunisia: ["Tunisia", "Tunisie", "Tunesien"],
  Turkey: ["Turkey", "Turchia", "Turquía", "Turquie", "Türkei", "Turquia"],
  Ukraine: ["Ukraine", "Ucraina", "Ucrania", "Ucrânia"],
  "United States": ["United States", "USA", "Stati Uniti", "Estados Unidos", "États-Unis", "Etats Unis", "America", "US"],
  Uruguay: ["Uruguay"],
  Wales: ["Wales", "Galles", "Gales", "Pays de Galles"],
  "Northern Ireland": ["Northern Ireland", "Irlanda del Nord", "Irlanda do Norte", "Irlande du Nord", "Nordirland"]
};

export const COUNTRY_ALIAS_OVERRIDES: Record<string, string[]> = {
  AR: ["Argentina"],
  AT: ["Austria"],
  AU: ["Australia"],
  BA: ["Bosnia", "Bosnia ed Erzegovina", "Bosnia and Herzegovina"],
  BE: ["Belgium", "Belgio", "Bélgica", "Belgique", "Belgien"],
  BR: ["Brazil", "Brasile", "Brasil", "Bresil", "Brésil", "Brasilien"],
  CH: ["Switzerland", "Svizzera", "Suiza", "Suisse", "Schweiz", "Suiça"],
  CL: ["Chile", "Cile"],
  CM: ["Cameroon", "Camerun", "Camerún", "Cameroun", "Kamerun"],
  CO: ["Colombia"],
  CR: ["Costa Rica"],
  CV: ["Cape Verde", "Capo Verde", "Cabo Verde", "Cap Vert", "Kap Verde"],
  CD: [
    "DR Congo",
    "RD Congo",
    "Congo DR",
    "Congo RD",
    "Democratic Republic of Congo",
    "Repubblica Democratica del Congo"
  ],
  CI: ["Ivory Coast", "Costa d'Avorio", "Costa d’Avorio", "Cote d Ivoire", "Côte d'Ivoire", "Côte d’Ivoire"],
  DE: ["Germany", "Germania", "Alemania", "Allemagne", "Deutschland", "Alemanha"],
  DK: ["Denmark", "Danimarca", "Dinamarca", "Danemark", "Dänemark"],
  EG: ["Egypt", "Egitto", "Egipto", "Égypte", "Agypten", "Ägypten", "Egito"],
  ES: ["Spain", "Spagna", "España", "Espana", "Espagne", "Spanien", "Espanha"],
  FR: ["France", "Francia", "França", "Frankreich"],
  GB: ["United Kingdom", "Regno Unito", "Gran Bretagna", "Great Britain", "UK"],
  GH: ["Ghana"],
  HR: ["Croatia", "Croazia", "Croacia", "Croatie", "Kroatien", "Croácia"],
  IT: ["Italy", "Italia", "Italie", "Italien", "Itália"],
  JP: ["Japan", "Giappone", "Japón", "Japon", "Japonia"],
  KR: ["South Korea", "Corea del Sud", "Corea Sud", "Korea Republic", "Republic of Korea", "Repubblica di Corea", "Corea"],
  MA: ["Morocco", "Marocco", "Marruecos", "Maroc", "Marokko", "Marrocos"],
  MX: ["Mexico", "Messico", "México", "Mexique", "Mexiko"],
  NG: ["Nigeria"],
  NL: ["Netherlands", "Olanda", "Paesi Bassi", "Holanda", "Países Bajos", "Paises Bajos", "Pays Bas", "Pays-Bas", "Holland", "Niederlande"],
  NZ: ["New Zealand", "Nuova Zelanda", "Nueva Zelanda", "Nouvelle-Zélande", "Nouvelle Zelande", "Neuseeland"],
  PL: ["Poland", "Polonia", "Polska", "Pologne", "Polen", "Polônia"],
  PT: ["Portugal", "Portogallo"],
  RS: ["Serbia"],
  SA: ["Saudi Arabia", "Arabia Saudita", "Arabia Saudí", "Arabie Saoudite", "Saudi-Arabien"],
  SN: ["Senegal"],
  TN: ["Tunisia", "Tunisie", "Tunesien"],
  TR: ["Turkey", "Turchia", "Turquía", "Turquie", "Türkei", "Turquia"],
  UA: ["Ukraine", "Ucraina", "Ucrania", "Ucrânia"],
  US: ["USA", "United States", "Stati Uniti", "Estados Unidos", "États-Unis", "Etats Unis", "Vereinigte Staaten", "America", "US"],
  UY: ["Uruguay"],
  ZA: ["South Africa", "Sudafrica", "Afrique du Sud", "Südafrika"],
  ENG: ["England", "Inghilterra", "Inglaterra", "Angleterre", "England"],
  SCO: ["Scotland", "Scozia", "Escocia", "Écosse", "Schottland"],
  WAL: ["Wales", "Galles", "Gales", "Pays de Galles", "Wales"],
  NIR: ["Northern Ireland", "Irlanda del Nord", "Irlanda do Norte", "Irlande du Nord", "Nordirland"]
};

export const DISPLAY_NAME_LOCALES = ["en", "it", "es", "fr", "de", "pt"] as const;
